
import MyCard from "@/components/molecules/my-card/my-card";
import "./globals.css";
import { Inter } from "next/font/google";
import CardStat from "@/components/molecules/card-stats/card-stat";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function Rootlayout({
  children,
}: {
  children: React.ReactNode; 
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
   
     <div>{children}</div></body>
    
    </html>
  );
}
